# Generated by Django 5.1.5 on 2026-03-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=100)),
                ('accuracy', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('completeness', models.IntegerField()),
                ('example_quality', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluations', to='tutor.tutorlog')),
            ],
        ),
    ]
