# Generated by Django 5.1.5 on 2026-03-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_rubricevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=100)),
                ('evaluated_module', models.CharField(default='overall', max_length=50)),
                ('completeness', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('correctness', models.IntegerField()),
                ('usefulness', models.IntegerField()),
                ('understanding_improvement', models.IntegerField()),
                ('quiz_relevance', models.IntegerField()),
                ('overall_satisfaction', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RubricEvaluation',
        ),
    ]
