# Generated by Django 5.1.5 on 2026-03-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutorevaluation_delete_rubricevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorevaluation',
            name='evaluated_module',
            field=models.CharField(choices=[('theory', 'Theory Module'), ('practical', 'Practical Module')], max_length=20),
        ),
    ]
