# Generated by Django 5.1.5 on 2026-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutorevaluation_evaluated_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorevaluation',
            old_name='clarity',
            new_name='q1_complete_explanations',
        ),
        migrations.RenameField(
            model_name='tutorevaluation',
            old_name='completeness',
            new_name='q2_improves_understanding',
        ),
        migrations.RenameField(
            model_name='tutorevaluation',
            old_name='correctness',
            new_name='q3_quiz_consistency',
        ),
        migrations.RenameField(
            model_name='tutorevaluation',
            old_name='overall_satisfaction',
            new_name='q4_response_reliability',
        ),
        migrations.RenameField(
            model_name='tutorevaluation',
            old_name='quiz_relevance',
            new_name='q5_useful_for_learning',
        ),
        migrations.RenameField(
            model_name='tutorevaluation',
            old_name='relevance',
            new_name='q6_increases_motivation',
        ),
        migrations.RenameField(
            model_name='tutorevaluation',
            old_name='understanding_improvement',
            new_name='q7_overall_satisfaction',
        ),
        migrations.RemoveField(
            model_name='tutorevaluation',
            name='usefulness',
        ),
        migrations.AddField(
            model_name='tutorlog',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
